/**
 * AcademicTermEnrollment trigger for creating action plans
 * Auto-generated by Action Plans
 */
trigger APAcademicTermEnrollment on AcademicTermEnrollment (after insert, after update) {
    // Call the Action Plan Trigger Utility to handle action plan creation
    ActionPlanTriggerUtility.invoke(AcademicTermEnrollment.SObjectType);
}