/**
 * ProgramEnrollment trigger for creating action plans
 * Auto-generated by Action Plans
 */
trigger APProgramEnrollment on ProgramEnrollment (after insert, after update) {
    // Call the Action Plan Trigger Utility to handle action plan creation
    ActionPlanTriggerUtility.invoke(ProgramEnrollment.SObjectType);
}